/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.javaParking.view.xulambs;

import br.com.javaParking.view.cliente.ClienteView;
import br.com.javaParking.view.parque.ParqueView;
import br.com.javaParking.view.xulambs.PdaView;
import br.com.javaParking.model.Configuracao;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JTable;

/**
 *
 * @author Leandro Alencar
 */
public class ArrecadacaoView extends javax.swing.JFrame {

    /**
     * Creates new form ViewPagamento
     */
    public ArrecadacaoView() {
        initComponents();
    }

    public JComboBox<String> getCbAno() {
        return cbAno;
    }

    public void setCbAno(JComboBox<String> cbAno) {
        this.cbAno = cbAno;
    }

    public JComboBox<String> getCbMes() {
        return cbMes;
    }

    public void setCbMes(JComboBox<String> cbMes) {
        this.cbMes = cbMes;
    }

    public JComboBox<String> getCbParque() {
        return cbParque;
    }

    public void setCbParque(JComboBox<String> cbParque) {
        this.cbParque = cbParque;
    }

    public JLabel getLblTotalArrecadado() {
        return lblTotalArrecadado;
    }

    public void setLblTotalArrecadado(JLabel lblTotalArrecadado) {
        this.lblTotalArrecadado = lblTotalArrecadado;
    }

    public JLabel getLblValorMedio() {
        return lblValorMedio;
    }

    public void setLblValorMedio(JLabel lblValorMedio) {
        this.lblValorMedio = lblValorMedio;
    }

    public JMenuItem getMenCadastroCliente() {
        return menCadastroCliente;
    }

    public void setMenCadastroCliente(JMenuItem menCadastroCliente) {
        this.menCadastroCliente = menCadastroCliente;
    }

    public JMenuItem getMenCadastroParque() {
        return menCadastroParque;
    }

    public void setMenCadastroParque(JMenuItem menCadastroParque) {
        this.menCadastroParque = menCadastroParque;
    }

    public JMenu getMenCadastros() {
        return menCadastros;
    }

    public void setMenCadastros(JMenu menCadastros) {
        this.menCadastros = menCadastros;
    }

    public JMenuItem getMenConfiguracao() {
        return menConfiguracao;
    }

    public void setMenConfiguracao(JMenuItem menConfiguracao) {
        this.menConfiguracao = menConfiguracao;
    }

    public JMenu getMenPDA() {
        return menPDA;
    }

    public void setMenPDA(JMenu menPDA) {
        this.menPDA = menPDA;
    }

    public JMenuItem getMenSair() {
        return menSair;
    }

    public void setMenSair(JMenuItem menSair) {
        this.menSair = menSair;
    }

    public JTable getTbArrecadacoes() {
        return tbArrecadacoes;
    }

    public void setTbArrecadacoes(JTable tbArrecadacoes) {
        this.tbArrecadacoes = tbArrecadacoes;
    }    

    public JMenuItem getMenPDAItem() {
        return menPDAItem;
    }

    public void setMenPDAItem(JMenuItem menPDAItem) {
        this.menPDAItem = menPDAItem;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblValorMedio = new javax.swing.JLabel();
        lblVendas = new javax.swing.JLabel();
        lblTotalArrecadado = new javax.swing.JLabel();
        lblVendas1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbArrecadacoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbAno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbParque = new javax.swing.JComboBox<>();
        Menu = new javax.swing.JMenuBar();
        menCadastros = new javax.swing.JMenu();
        menCadastroParque = new javax.swing.JMenuItem();
        menCadastroCliente = new javax.swing.JMenuItem();
        menPDA = new javax.swing.JMenu();
        menPDAItem = new javax.swing.JMenuItem();
        MenOpc = new javax.swing.JMenu();
        menConfiguracao = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xumlabs Parking");

        jPanel7.setBackground(java.awt.SystemColor.control);

        jPanel10.setBackground(java.awt.SystemColor.control);
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jPanel11.setBackground(java.awt.SystemColor.control);
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        jPanel9.setBackground(java.awt.SystemColor.control);
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(153, 153, 153)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 3, 12))); // NOI18N

        jPanel4.setBackground(java.awt.SystemColor.control);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        lblValorMedio.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblValorMedio.setForeground(new java.awt.Color(0, 0, 204));
        lblValorMedio.setText("0.00");

        lblVendas.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblVendas.setText(" Valor medio de ultilização: R$");

        lblTotalArrecadado.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTotalArrecadado.setForeground(new java.awt.Color(0, 153, 102));
        lblTotalArrecadado.setText("0.00");

        lblVendas1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblVendas1.setText(" Total Arregadado: R$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblVendas)
                .addGap(0, 0, 0)
                .addComponent(lblValorMedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVendas1)
                .addGap(0, 0, 0)
                .addComponent(lblTotalArrecadado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblValorMedio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalArrecadado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(lblVendas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel8.setBackground(java.awt.SystemColor.control);
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(153, 153, 153)), "Arrecadações", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 3, 12))); // NOI18N

        tbArrecadacoes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbArrecadacoes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tbArrecadacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbArrecadacoes.setFocusable(false);
        tbArrecadacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbArrecadacoesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbArrecadacoes);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel1.setText("PARQUE");

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setText("MÊS");

        cbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        cbAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setText("ANO");

        cbParque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        cbParque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbParqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(cbParque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbParque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Menu.setBackground(java.awt.SystemColor.control);
        Menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        Menu.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        menCadastros.setText("Gerenciar");
        menCadastros.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        menCadastroParque.setText("Parques");
        menCadastroParque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroParqueActionPerformed(evt);
            }
        });
        menCadastros.add(menCadastroParque);

        menCadastroCliente.setText("Clientes");
        menCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroClienteActionPerformed(evt);
            }
        });
        menCadastros.add(menCadastroCliente);

        Menu.add(menCadastros);

        menPDA.setText("PDA");
        menPDA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        menPDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menPDAMouseClicked(evt);
            }
        });
        menPDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPDAActionPerformed(evt);
            }
        });

        menPDAItem.setText("PDA");
        menPDAItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPDAItemActionPerformed(evt);
            }
        });
        menPDA.add(menPDAItem);

        Menu.add(menPDA);

        MenOpc.setText("Opções");
        MenOpc.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        menConfiguracao.setText("Configurações");
        menConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menConfiguracaoActionPerformed(evt);
            }
        });
        MenOpc.add(menConfiguracao);

        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        MenOpc.add(menSair);

        Menu.add(MenOpc);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbArrecadacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbArrecadacoesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbArrecadacoesMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed

    private void cbAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnoActionPerformed

    private void cbParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbParqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbParqueActionPerformed

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menSairActionPerformed

    private void menConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menConfiguracaoActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_menConfiguracaoActionPerformed

    private void menPDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menPDAActionPerformed

    private void menPDAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menPDAMouseClicked
        // TODO add your handling code here:      
    }//GEN-LAST:event_menPDAMouseClicked

    private void menCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroClienteActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_menCadastroClienteActionPerformed

    private void menCadastroParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroParqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadastroParqueActionPerformed

    private void menPDAItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPDAItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menPDAItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenOpc;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbParque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotalArrecadado;
    private javax.swing.JLabel lblValorMedio;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JLabel lblVendas1;
    private javax.swing.JMenuItem menCadastroCliente;
    private javax.swing.JMenuItem menCadastroParque;
    private javax.swing.JMenu menCadastros;
    private javax.swing.JMenuItem menConfiguracao;
    private javax.swing.JMenu menPDA;
    private javax.swing.JMenuItem menPDAItem;
    private javax.swing.JMenuItem menSair;
    private javax.swing.JTable tbArrecadacoes;
    // End of variables declaration//GEN-END:variables
}
